name: CI/CD

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List current directory contents
      run: ls -al

    - name: Run script.sh
      run: bash script.sh

  list-contents:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List current directory contents
      run: ls -al

    - name: Run script.sh
      run: bash script.sh
